branches:
  only:
    - master

sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - docker pull debian:testing

script:
  - docker -f ci/Dockerfile build -t withgit .
  - docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson builddir
    && ninja -C builddir && pip3 install -r ./python/requirements.txt && pip3 install
    ./python && ninja -C builddir test"

after_success:
  - ci/travisscripts/tagdev.sh $encrypted_d3e286bb4746_key $encrypted_d3e286bb4746_iv

