sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - docker pull debian:testing

script:
  - docker build -t withgit .
  - docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson builddir && ninja -C builddir && pip3 install -r ./python/requirements.txt && pip3 install ./python && ninja -C builddir test"
