#!/usr/bin/env python3

import argparse
import nodectrl.sourcevalidation
import json

parser = argparse.ArgumentParser()
parser.add_argument('--cert', type=argparse.FileType('r'), required=True)
parser.add_argument('--key', type=argparse.FileType('r'), required=True)
parser.add_argument('--action', type=str, required=True)

args = parser.parse_args()

payload = {}

topic = nodectrl.sourcevalidation.signmsg(args.cert, args.key, "omnomnom", 'my/topic',
                                          json.dumps(payload).encode('utf-8'))

print(topic)
